// A lightweight, offline stand-in for the real Grok extraction.
// It does simple keyword matching so the UI is fully demoable with no backend.
// The real profiling happens server-side; this just mirrors the shape.

import { ExperienceLevel, LearnerProfile } from "./types";

const ROLES: Record<string, string> = {
  "data analyst": "Data Analyst",
  "data scientist": "Data Scientist",
  "machine learning": "Machine Learning Engineer",
  "ml engineer": "Machine Learning Engineer",
  "web developer": "Web Developer",
  "frontend": "Frontend Developer",
  "front-end": "Frontend Developer",
  "backend": "Backend Developer",
  "full stack": "Full-Stack Developer",
  "designer": "Product Designer",
  "devops": "DevOps Engineer",
};

const SKILLS = [
  "python", "sql", "excel", "javascript", "typescript", "react", "node",
  "java", "c++", "html", "css", "pandas", "numpy", "docker", "aws",
  "tableau", "power bi", "figma", "git", "statistics",
];

const FORMATS = ["video", "reading", "project", "interactive", "book", "course"];

function detectLevel(text: string): ExperienceLevel | null {
  if (/\b(advanced|expert|senior|years of experience|professional)\b/.test(text)) return "advanced";
  if (/\b(intermediate|some experience|familiar|a bit of|comfortable)\b/.test(text)) return "intermediate";
  if (/\b(beginner|new to|just starting|no experience|never|little)\b/.test(text)) return "beginner";
  return null;
}

function unique<T>(arr: T[]): T[] {
  return Array.from(new Set(arr));
}

/**
 * Merge new findings from `message` into the existing profile and return a copy.
 */
export function demoExtract(message: string, prev: LearnerProfile): LearnerProfile {
  const text = message.toLowerCase();
  const next: LearnerProfile = structuredClone(prev);

  // target role
  for (const [needle, role] of Object.entries(ROLES)) {
    if (text.includes(needle)) {
      next.goals.target_role = role;
      if (!next.interests.includes(role)) next.interests.push(role);
    }
  }

  // experience level
  const level = detectLevel(text);
  if (level) next.experience_level = level;

  // skills — add any mentioned that we don't already track
  const known = new Set(next.current_skills.map((s) => s.skill));
  for (const skill of SKILLS) {
    if (text.includes(skill) && !known.has(skill)) {
      // rough proficiency guess from the message's tone
      const prof = level === "advanced" ? 4 : level === "intermediate" ? 3 : 2;
      next.current_skills.push({ skill, proficiency: prof });
    }
  }

  // time commitment e.g. "5 hours a week", "10 hrs/week"
  const time = text.match(/(\d+)\s*(?:hours?|hrs?)\s*(?:a|per|\/)?\s*week/);
  if (time) next.preferences.time_commitment = `${time[1]} hours/week`;

  // preferred formats
  const formats = FORMATS.filter((f) => text.includes(f));
  if (formats.length) {
    next.preferences.preferred_formats = unique([
      ...(next.preferences.preferred_formats ?? []),
      ...formats,
    ]);
  }

  // goals — keep the latest message as raw_text, collect a parsed goal
  next.goals.raw_text = message;
  if (next.goals.target_role) {
    const g = `become a ${next.goals.target_role}`;
    if (!next.goals.parsed.includes(g)) next.goals.parsed.push(g);
  }
  const learnMatch = text.match(/learn ([a-z0-9 +#]+)/);
  if (learnMatch) {
    const g = `learn ${learnMatch[1].trim().split(/[.,]/)[0]}`;
    if (!next.goals.parsed.includes(g)) next.goals.parsed.push(g);
  }

  next.updated_at = new Date().toISOString();
  return next;
}

/** True when the learner is asking to see their roadmap. */
export function isPathRequest(message: string): boolean {
  return /learning path|roadmap|my path|next steps?/i.test(message);
}

/** A stand-in path preview. The real generator is a separate feature. */
export function demoPathReply(p: LearnerProfile): string {
  const goal = p.goals.target_role ?? "your goal";
  const have = p.current_skills.map((s) => s.skill).join(", ") || "the basics";
  return `Here's the shape of your path toward ${goal}: build on what you have (${have}), close the gaps with focused courses, then prove it with a project. The full step-by-step roadmap is generated by the recommendation engine — this preview shows your path is ready to build.`;
}

/** A short, friendly summary reply — mirrors the backend's _build_reply. */
export function demoReply(p: LearnerProfile): string {
  const bits: string[] = [];
  if (p.goals.target_role) bits.push(`aiming to become a ${p.goals.target_role}`);
  bits.push(`at a ${p.experience_level} level`);
  if (p.current_skills.length) {
    bits.push(`with some ${p.current_skills.map((s) => s.skill).join(", ")}`);
  }
  return `Got it — I've noted you're ${bits.join("; ")}. Tell me more, or ask for your learning path.`;
}
